/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ProductCategory = IDL.Variant({
  'ayurvedicCare' : IDL.Null,
  'immunity' : IDL.Null,
  'digestiveHealth' : IDL.Null,
  'fitness' : IDL.Null,
  'multivitamins' : IDL.Null,
  'herbalSupplements' : IDL.Null,
});
export const Product = IDL.Record({
  'id' : IDL.Text,
  'featured' : IDL.Bool,
  'inStock' : IDL.Bool,
  'name' : IDL.Text,
  'howToUse' : IDL.Text,
  'imageUrl' : IDL.Text,
  'shortDescription' : IDL.Text,
  'category' : ProductCategory,
  'benefits' : IDL.Vec(IDL.Text),
  'safetyInfo' : IDL.Text,
  'fullDescription' : IDL.Text,
  'price' : IDL.Nat,
  'ingredients' : IDL.Vec(IDL.Text),
});
export const Address = IDL.Record({
  'city' : IDL.Text,
  'line1' : IDL.Text,
  'line2' : IDL.Text,
  'state' : IDL.Text,
  'pincode' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CafResult_1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
export const CustomerDetails = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const PaymentMethod = IDL.Variant({
  'cod' : IDL.Null,
  'upi' : IDL.Null,
  'netbanking' : IDL.Null,
  'card' : IDL.Null,
});
export const ProductInput = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'howToUse' : IDL.Text,
  'stock' : IDL.Nat,
  'imageUrl' : IDL.Text,
  'isFeatured' : IDL.Bool,
  'category' : ProductCategory,
  'benefits' : IDL.Text,
  'safetyInfo' : IDL.Text,
  'price' : IDL.Nat,
  'ingredients' : IDL.Text,
});
export const CafResult = IDL.Variant({ 'ok' : Product, 'err' : IDL.Text });
export const Time = IDL.Int;
export const OrderStatus = IDL.Variant({
  'shipped' : IDL.Null,
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'delivered' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const ReturnReason = IDL.Variant({
  'DamagedInShipment' : IDL.Null,
  'WrongProduct' : IDL.Null,
  'Defective' : IDL.Null,
});
export const ReturnRequest = IDL.Record({
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  }),
  'requestId' : IDL.Text,
  'requestType' : IDL.Variant({
    'replace' : IDL.Null,
    'returnItem' : IDL.Null,
  }),
  'requestedAt' : Time,
  'reason' : ReturnReason,
});
export const ProductWithQuantity = IDL.Record({
  'quantity' : IDL.Nat,
  'price' : IDL.Nat,
  'product' : Product,
});
export const Order = IDL.Record({
  'paymentMethod' : PaymentMethod,
  'deliveredAt' : IDL.Opt(Time),
  'orderStatus' : OrderStatus,
  'userId' : IDL.Principal,
  'createdAt' : Time,
  'orderId' : IDL.Text,
  'updatedAt' : Time,
  'totalAmount' : IDL.Nat,
  'customerDetails' : CustomerDetails,
  'shippingAddress' : Address,
  'returnRequests' : IDL.Vec(ReturnRequest),
  'cancelReason' : IDL.Opt(IDL.Text),
  'items' : IDL.Vec(ProductWithQuantity),
});
export const UserProfile = IDL.Record({
  'userId' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : Time,
  'savedAddresses' : IDL.Vec(Address),
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const CafResult_2 = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addProduct' : IDL.Func([Product], [], []),
  'addSavedAddress' : IDL.Func([Address], [], []),
  'addToCart' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'canCancelOrder' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'canReturnOrder' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'cancelOrder' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [CafResult_1], []),
  'clearCart' : IDL.Func([], [], []),
  'createOrUpdateProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'createOrder' : IDL.Func(
      [CustomerDetails, Address, PaymentMethod],
      [IDL.Text],
      [],
    ),
  'createProduct' : IDL.Func([ProductInput], [CafResult], []),
  'deleteProduct' : IDL.Func([IDL.Text], [CafResult_1], []),
  'deleteSavedAddress' : IDL.Func([IDL.Nat], [], []),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getAnalyticsSummary' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalProducts' : IDL.Nat,
          'totalOrders' : IDL.Nat,
          'totalRevenue' : IDL.Nat,
          'avgOrderValue' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCart' : IDL.Func(
      [],
      [
        IDL.Record({
          'items' : IDL.Vec(ProductWithQuantity),
          'subtotal' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getFeaturedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getOrderById' : IDL.Func([IDL.Text], [Order], ['query']),
  'getOrdersByDay' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'getOrdersByStatus' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'getPaymentMethodBreakdown' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'getProduct' : IDL.Func([IDL.Text], [Product], ['query']),
  'getRevenueByDay' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'getTopSellingProducts' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'getUserOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllProductsAdmin' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'listProducts' : IDL.Func(
      [IDL.Opt(ProductCategory)],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'removeFromCart' : IDL.Func([IDL.Text], [], []),
  'requestReplace' : IDL.Func([IDL.Text, ReturnReason], [CafResult_2], []),
  'requestReturn' : IDL.Func([IDL.Text, ReturnReason], [CafResult_2], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setFeatured' : IDL.Func([IDL.Text, IDL.Bool], [CafResult_1], []),
  'updateCartItemQuantity' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'updateOrderStatus' : IDL.Func([IDL.Text, OrderStatus], [], []),
  'updateProduct' : IDL.Func([IDL.Text, ProductInput], [CafResult], []),
  'updateProductStock' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'updateSavedAddress' : IDL.Func([IDL.Nat, Address], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ProductCategory = IDL.Variant({
    'ayurvedicCare' : IDL.Null,
    'immunity' : IDL.Null,
    'digestiveHealth' : IDL.Null,
    'fitness' : IDL.Null,
    'multivitamins' : IDL.Null,
    'herbalSupplements' : IDL.Null,
  });
  const Product = IDL.Record({
    'id' : IDL.Text,
    'featured' : IDL.Bool,
    'inStock' : IDL.Bool,
    'name' : IDL.Text,
    'howToUse' : IDL.Text,
    'imageUrl' : IDL.Text,
    'shortDescription' : IDL.Text,
    'category' : ProductCategory,
    'benefits' : IDL.Vec(IDL.Text),
    'safetyInfo' : IDL.Text,
    'fullDescription' : IDL.Text,
    'price' : IDL.Nat,
    'ingredients' : IDL.Vec(IDL.Text),
  });
  const Address = IDL.Record({
    'city' : IDL.Text,
    'line1' : IDL.Text,
    'line2' : IDL.Text,
    'state' : IDL.Text,
    'pincode' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CafResult_1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  const CustomerDetails = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const PaymentMethod = IDL.Variant({
    'cod' : IDL.Null,
    'upi' : IDL.Null,
    'netbanking' : IDL.Null,
    'card' : IDL.Null,
  });
  const ProductInput = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'howToUse' : IDL.Text,
    'stock' : IDL.Nat,
    'imageUrl' : IDL.Text,
    'isFeatured' : IDL.Bool,
    'category' : ProductCategory,
    'benefits' : IDL.Text,
    'safetyInfo' : IDL.Text,
    'price' : IDL.Nat,
    'ingredients' : IDL.Text,
  });
  const CafResult = IDL.Variant({ 'ok' : Product, 'err' : IDL.Text });
  const Time = IDL.Int;
  const OrderStatus = IDL.Variant({
    'shipped' : IDL.Null,
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'delivered' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const ReturnReason = IDL.Variant({
    'DamagedInShipment' : IDL.Null,
    'WrongProduct' : IDL.Null,
    'Defective' : IDL.Null,
  });
  const ReturnRequest = IDL.Record({
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'approved' : IDL.Null,
      'rejected' : IDL.Null,
    }),
    'requestId' : IDL.Text,
    'requestType' : IDL.Variant({
      'replace' : IDL.Null,
      'returnItem' : IDL.Null,
    }),
    'requestedAt' : Time,
    'reason' : ReturnReason,
  });
  const ProductWithQuantity = IDL.Record({
    'quantity' : IDL.Nat,
    'price' : IDL.Nat,
    'product' : Product,
  });
  const Order = IDL.Record({
    'paymentMethod' : PaymentMethod,
    'deliveredAt' : IDL.Opt(Time),
    'orderStatus' : OrderStatus,
    'userId' : IDL.Principal,
    'createdAt' : Time,
    'orderId' : IDL.Text,
    'updatedAt' : Time,
    'totalAmount' : IDL.Nat,
    'customerDetails' : CustomerDetails,
    'shippingAddress' : Address,
    'returnRequests' : IDL.Vec(ReturnRequest),
    'cancelReason' : IDL.Opt(IDL.Text),
    'items' : IDL.Vec(ProductWithQuantity),
  });
  const UserProfile = IDL.Record({
    'userId' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : Time,
    'savedAddresses' : IDL.Vec(Address),
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const CafResult_2 = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addProduct' : IDL.Func([Product], [], []),
    'addSavedAddress' : IDL.Func([Address], [], []),
    'addToCart' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'canCancelOrder' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'canReturnOrder' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'cancelOrder' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [CafResult_1], []),
    'clearCart' : IDL.Func([], [], []),
    'createOrUpdateProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'createOrder' : IDL.Func(
        [CustomerDetails, Address, PaymentMethod],
        [IDL.Text],
        [],
      ),
    'createProduct' : IDL.Func([ProductInput], [CafResult], []),
    'deleteProduct' : IDL.Func([IDL.Text], [CafResult_1], []),
    'deleteSavedAddress' : IDL.Func([IDL.Nat], [], []),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getAnalyticsSummary' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalProducts' : IDL.Nat,
            'totalOrders' : IDL.Nat,
            'totalRevenue' : IDL.Nat,
            'avgOrderValue' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCart' : IDL.Func(
        [],
        [
          IDL.Record({
            'items' : IDL.Vec(ProductWithQuantity),
            'subtotal' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getFeaturedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getOrderById' : IDL.Func([IDL.Text], [Order], ['query']),
    'getOrdersByDay' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'getOrdersByStatus' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'getPaymentMethodBreakdown' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'getProduct' : IDL.Func([IDL.Text], [Product], ['query']),
    'getRevenueByDay' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'getTopSellingProducts' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'getUserOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllProductsAdmin' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'listProducts' : IDL.Func(
        [IDL.Opt(ProductCategory)],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'removeFromCart' : IDL.Func([IDL.Text], [], []),
    'requestReplace' : IDL.Func([IDL.Text, ReturnReason], [CafResult_2], []),
    'requestReturn' : IDL.Func([IDL.Text, ReturnReason], [CafResult_2], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setFeatured' : IDL.Func([IDL.Text, IDL.Bool], [CafResult_1], []),
    'updateCartItemQuantity' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'updateOrderStatus' : IDL.Func([IDL.Text, OrderStatus], [], []),
    'updateProduct' : IDL.Func([IDL.Text, ProductInput], [CafResult], []),
    'updateProductStock' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'updateSavedAddress' : IDL.Func([IDL.Nat, Address], [], []),
  });
};

export const init = ({ IDL }) => { return []; };