/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Address {
  'city' : string,
  'line1' : string,
  'line2' : string,
  'state' : string,
  'pincode' : string,
}
export type CafResult = { 'ok' : Product } |
  { 'err' : string };
export type CafResult_1 = { 'ok' : null } |
  { 'err' : string };
export interface CustomerDetails {
  'name' : string,
  'email' : string,
  'phone' : string,
}
export interface Order {
  'paymentMethod' : PaymentMethod,
  'orderStatus' : OrderStatus,
  'userId' : Principal,
  'createdAt' : Time,
  'orderId' : string,
  'updatedAt' : Time,
  'totalAmount' : bigint,
  'customerDetails' : CustomerDetails,
  'shippingAddress' : Address,
  'items' : Array<ProductWithQuantity>,
}
export type OrderStatus = { 'shipped' : null } |
  { 'cancelled' : null } |
  { 'pending' : null } |
  { 'delivered' : null } |
  { 'confirmed' : null };
export type PaymentMethod = { 'cod' : null } |
  { 'upi' : null } |
  { 'netbanking' : null } |
  { 'card' : null };
export interface Product {
  'id' : string,
  'featured' : boolean,
  'inStock' : boolean,
  'name' : string,
  'howToUse' : string,
  'imageUrl' : string,
  'shortDescription' : string,
  'category' : ProductCategory,
  'benefits' : Array<string>,
  'safetyInfo' : string,
  'fullDescription' : string,
  'price' : bigint,
  'ingredients' : Array<string>,
}
export type ProductCategory = { 'ayurvedicCare' : null } |
  { 'immunity' : null } |
  { 'digestiveHealth' : null } |
  { 'fitness' : null } |
  { 'multivitamins' : null } |
  { 'herbalSupplements' : null };
export interface ProductInput {
  'name' : string,
  'description' : string,
  'howToUse' : string,
  'stock' : bigint,
  'imageUrl' : string,
  'isFeatured' : boolean,
  'category' : ProductCategory,
  'benefits' : string,
  'safetyInfo' : string,
  'price' : bigint,
  'ingredients' : string,
}
export interface ProductWithQuantity {
  'quantity' : bigint,
  'price' : bigint,
  'product' : Product,
}
export type Time = bigint;
export interface UserProfile {
  'userId' : Principal,
  'name' : string,
  'createdAt' : Time,
  'savedAddresses' : Array<Address>,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addProduct' : ActorMethod<[Product], undefined>,
  'addSavedAddress' : ActorMethod<[Address], undefined>,
  'addToCart' : ActorMethod<[string, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearCart' : ActorMethod<[], undefined>,
  'createOrUpdateProfile' : ActorMethod<[string, string, string], undefined>,
  'createOrder' : ActorMethod<
    [CustomerDetails, Address, PaymentMethod],
    string
  >,
  'createProduct' : ActorMethod<[ProductInput], CafResult>,
  'deleteProduct' : ActorMethod<[string], CafResult_1>,
  'deleteSavedAddress' : ActorMethod<[bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCart' : ActorMethod<
    [],
    { 'items' : Array<ProductWithQuantity>, 'subtotal' : bigint }
  >,
  'getFeaturedProducts' : ActorMethod<[], Array<Product>>,
  'getOrderById' : ActorMethod<[string], Order>,
  'getProduct' : ActorMethod<[string], Product>,
  'getUserOrders' : ActorMethod<[], Array<Order>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isAdmin' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAllProductsAdmin' : ActorMethod<[], Array<Product>>,
  'listProducts' : ActorMethod<[[] | [ProductCategory]], Array<Product>>,
  'removeFromCart' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setFeatured' : ActorMethod<[string, boolean], CafResult_1>,
  'updateCartItemQuantity' : ActorMethod<[string, bigint], undefined>,
  'updateOrderStatus' : ActorMethod<[string, OrderStatus], undefined>,
  'updateProduct' : ActorMethod<[string, ProductInput], CafResult>,
  'updateProductStock' : ActorMethod<[string, boolean], undefined>,
  'updateSavedAddress' : ActorMethod<[bigint, Address], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];