/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface CustomerDetails {
    name: string;
    email: string;
    phone: string;
}
export interface ProductInput {
    name: string;
    description: string;
    howToUse: string;
    stock: bigint;
    imageUrl: string;
    isFeatured: boolean;
    category: ProductCategory;
    benefits: string;
    safetyInfo: string;
    price: bigint;
    ingredients: string;
}
export type CafResult_1 = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
};
export type Time = bigint;
export interface Address {
    city: string;
    line1: string;
    line2: string;
    state: string;
    pincode: string;
}
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface ReturnRequest {
    status: Variant_pending_approved_rejected;
    requestId: string;
    requestType: Variant_replace_returnItem;
    requestedAt: Time;
    reason: ReturnReason;
}
export interface Order {
    paymentMethod: PaymentMethod;
    deliveredAt?: Time;
    orderStatus: OrderStatus;
    userId: Principal;
    createdAt: Time;
    orderId: string;
    updatedAt: Time;
    totalAmount: bigint;
    customerDetails: CustomerDetails;
    shippingAddress: Address;
    returnRequests: Array<ReturnRequest>;
    cancelReason?: string;
    items: Array<ProductWithQuantity>;
}
export type CafResult = {
    __kind__: "ok";
    ok: Product;
} | {
    __kind__: "err";
    err: string;
};
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export type CafResult_2 = {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
};
export interface ProductWithQuantity {
    quantity: bigint;
    price: bigint;
    product: Product;
}
export interface Product {
    id: string;
    featured: boolean;
    inStock: boolean;
    name: string;
    howToUse: string;
    imageUrl: string;
    shortDescription: string;
    category: ProductCategory;
    benefits: Array<string>;
    safetyInfo: string;
    fullDescription: string;
    price: bigint;
    ingredients: Array<string>;
}
export interface UserProfile {
    userId: Principal;
    name: string;
    createdAt: Time;
    savedAddresses: Array<Address>;
    email: string;
    phone: string;
}
export enum OrderStatus {
    shipped = "shipped",
    cancelled = "cancelled",
    pending = "pending",
    delivered = "delivered",
    confirmed = "confirmed"
}
export enum PaymentMethod {
    cod = "cod",
    upi = "upi",
    netbanking = "netbanking",
    card = "card"
}
export enum ProductCategory {
    ayurvedicCare = "ayurvedicCare",
    immunity = "immunity",
    digestiveHealth = "digestiveHealth",
    fitness = "fitness",
    multivitamins = "multivitamins",
    herbalSupplements = "herbalSupplements"
}
export enum ReturnReason {
    DamagedInShipment = "DamagedInShipment",
    WrongProduct = "WrongProduct",
    Defective = "Defective"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_pending_approved_rejected {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum Variant_replace_returnItem {
    replace = "replace",
    returnItem = "returnItem"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControl(): Promise<void>;
    addProduct(product: Product): Promise<void>;
    addSavedAddress(address: Address): Promise<void>;
    addToCart(productId: string, quantity: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    canCancelOrder(orderId: string): Promise<boolean>;
    canReturnOrder(orderId: string): Promise<boolean>;
    cancelOrder(orderId: string, reason: string | null): Promise<CafResult_1>;
    clearCart(): Promise<void>;
    createOrUpdateProfile(name: string, email: string, phone: string): Promise<void>;
    createOrder(customerDetails: CustomerDetails, shippingAddress: Address, paymentMethod: PaymentMethod): Promise<string>;
    createProduct(input: ProductInput): Promise<CafResult>;
    deleteProduct(id: string): Promise<CafResult_1>;
    deleteSavedAddress(index: bigint): Promise<void>;
    getAllOrders(): Promise<Array<Order>>;
    getAnalyticsSummary(): Promise<{
        totalProducts: bigint;
        totalOrders: bigint;
        totalRevenue: bigint;
        avgOrderValue: bigint;
    }>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCart(): Promise<{
        items: Array<ProductWithQuantity>;
        subtotal: bigint;
    }>;
    getFeaturedProducts(): Promise<Array<Product>>;
    getOrderById(orderId: string): Promise<Order>;
    getOrdersByDay(days: bigint): Promise<Array<[string, bigint]>>;
    getOrdersByStatus(): Promise<Array<[string, bigint]>>;
    getPaymentMethodBreakdown(): Promise<Array<[string, bigint]>>;
    getProduct(id: string): Promise<Product>;
    getRevenueByDay(days: bigint): Promise<Array<[string, bigint]>>;
    getTopSellingProducts(limit: bigint): Promise<Array<[string, string, bigint]>>;
    getUserOrders(): Promise<Array<Order>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isAdmin(): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    listAllProductsAdmin(): Promise<Array<Product>>;
    listProducts(category: ProductCategory | null): Promise<Array<Product>>;
    removeFromCart(productId: string): Promise<void>;
    requestReplace(orderId: string, reason: ReturnReason): Promise<CafResult_2>;
    requestReturn(orderId: string, reason: ReturnReason): Promise<CafResult_2>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setFeatured(id: string, featured: boolean): Promise<CafResult_1>;
    updateCartItemQuantity(productId: string, quantity: bigint): Promise<void>;
    updateOrderStatus(orderId: string, newStatus: OrderStatus): Promise<void>;
    updateProduct(id: string, input: ProductInput): Promise<CafResult>;
    updateProductStock(productId: string, inStock: boolean): Promise<void>;
    updateSavedAddress(index: bigint, address: Address): Promise<void>;
}
import type { Address as _Address, CafResult as _CafResult, CafResult_1 as _CafResult_1, CafResult_2 as _CafResult_2, CustomerDetails as _CustomerDetails, Order as _Order, OrderStatus as _OrderStatus, PaymentMethod as _PaymentMethod, Product as _Product, ProductCategory as _ProductCategory, ProductInput as _ProductInput, ProductWithQuantity as _ProductWithQuantity, ReturnReason as _ReturnReason, ReturnRequest as _ReturnRequest, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async addProduct(arg0: Product): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addProduct(to_candid_Product_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProduct(to_candid_Product_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addSavedAddress(arg0: Address): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addSavedAddress(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSavedAddress(arg0);
            return result;
        }
    }
    async addToCart(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addToCart(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addToCart(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n12(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n12(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async canCancelOrder(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.canCancelOrder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.canCancelOrder(arg0);
            return result;
        }
    }
    async canReturnOrder(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.canReturnOrder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.canReturnOrder(arg0);
            return result;
        }
    }
    async cancelOrder(arg0: string, arg1: string | null): Promise<CafResult_1> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelOrder(arg0, to_candid_opt_n14(this._uploadFile, this._downloadFile, arg1));
                return from_candid_CafResult_1_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelOrder(arg0, to_candid_opt_n14(this._uploadFile, this._downloadFile, arg1));
            return from_candid_CafResult_1_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async clearCart(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearCart();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearCart();
            return result;
        }
    }
    async createOrUpdateProfile(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrUpdateProfile(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrUpdateProfile(arg0, arg1, arg2);
            return result;
        }
    }
    async createOrder(arg0: CustomerDetails, arg1: Address, arg2: PaymentMethod): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrder(arg0, arg1, to_candid_PaymentMethod_n17(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrder(arg0, arg1, to_candid_PaymentMethod_n17(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async createProduct(arg0: ProductInput): Promise<CafResult> {
        if (this.processError) {
            try {
                const result = await this.actor.createProduct(to_candid_ProductInput_n19(this._uploadFile, this._downloadFile, arg0));
                return from_candid_CafResult_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProduct(to_candid_ProductInput_n19(this._uploadFile, this._downloadFile, arg0));
            return from_candid_CafResult_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteProduct(arg0: string): Promise<CafResult_1> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProduct(arg0);
                return from_candid_CafResult_1_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProduct(arg0);
            return from_candid_CafResult_1_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteSavedAddress(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSavedAddress(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSavedAddress(arg0);
            return result;
        }
    }
    async getAllOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllOrders();
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllOrders();
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAnalyticsSummary(): Promise<{
        totalProducts: bigint;
        totalOrders: bigint;
        totalRevenue: bigint;
        avgOrderValue: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnalyticsSummary();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnalyticsSummary();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCart(): Promise<{
        items: Array<ProductWithQuantity>;
        subtotal: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getCart();
                return from_candid_record_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCart();
            return from_candid_record_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFeaturedProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeaturedProducts();
                return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeaturedProducts();
            return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrderById(arg0: string): Promise<Order> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrderById(arg0);
                return from_candid_Order_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrderById(arg0);
            return from_candid_Order_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrdersByDay(arg0: bigint): Promise<Array<[string, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrdersByDay(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrdersByDay(arg0);
            return result;
        }
    }
    async getOrdersByStatus(): Promise<Array<[string, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrdersByStatus();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrdersByStatus();
            return result;
        }
    }
    async getPaymentMethodBreakdown(): Promise<Array<[string, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPaymentMethodBreakdown();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPaymentMethodBreakdown();
            return result;
        }
    }
    async getProduct(arg0: string): Promise<Product> {
        if (this.processError) {
            try {
                const result = await this.actor.getProduct(arg0);
                return from_candid_Product_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProduct(arg0);
            return from_candid_Product_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRevenueByDay(arg0: bigint): Promise<Array<[string, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRevenueByDay(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRevenueByDay(arg0);
            return result;
        }
    }
    async getTopSellingProducts(arg0: bigint): Promise<Array<[string, string, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTopSellingProducts(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTopSellingProducts(arg0);
            return result;
        }
    }
    async getUserOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserOrders();
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserOrders();
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async isAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAdmin();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listAllProductsAdmin(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllProductsAdmin();
                return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllProductsAdmin();
            return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async listProducts(arg0: ProductCategory | null): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.listProducts(to_candid_opt_n51(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listProducts(to_candid_opt_n51(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeFromCart(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFromCart(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFromCart(arg0);
            return result;
        }
    }
    async requestReplace(arg0: string, arg1: ReturnReason): Promise<CafResult_2> {
        if (this.processError) {
            try {
                const result = await this.actor.requestReplace(arg0, to_candid_ReturnReason_n52(this._uploadFile, this._downloadFile, arg1));
                return from_candid_CafResult_2_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestReplace(arg0, to_candid_ReturnReason_n52(this._uploadFile, this._downloadFile, arg1));
            return from_candid_CafResult_2_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async requestReturn(arg0: string, arg1: ReturnReason): Promise<CafResult_2> {
        if (this.processError) {
            try {
                const result = await this.actor.requestReturn(arg0, to_candid_ReturnReason_n52(this._uploadFile, this._downloadFile, arg1));
                return from_candid_CafResult_2_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestReturn(arg0, to_candid_ReturnReason_n52(this._uploadFile, this._downloadFile, arg1));
            return from_candid_CafResult_2_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setFeatured(arg0: string, arg1: boolean): Promise<CafResult_1> {
        if (this.processError) {
            try {
                const result = await this.actor.setFeatured(arg0, arg1);
                return from_candid_CafResult_1_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setFeatured(arg0, arg1);
            return from_candid_CafResult_1_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateCartItemQuantity(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCartItemQuantity(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCartItemQuantity(arg0, arg1);
            return result;
        }
    }
    async updateOrderStatus(arg0: string, arg1: OrderStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n56(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n56(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateProduct(arg0: string, arg1: ProductInput): Promise<CafResult> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProduct(arg0, to_candid_ProductInput_n19(this._uploadFile, this._downloadFile, arg1));
                return from_candid_CafResult_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProduct(arg0, to_candid_ProductInput_n19(this._uploadFile, this._downloadFile, arg1));
            return from_candid_CafResult_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateProductStock(arg0: string, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProductStock(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProductStock(arg0, arg1);
            return result;
        }
    }
    async updateSavedAddress(arg0: bigint, arg1: Address): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSavedAddress(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSavedAddress(arg0, arg1);
            return result;
        }
    }
}
function from_candid_CafResult_1_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CafResult_1): CafResult_1 {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_CafResult_2_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CafResult_2): CafResult_2 {
    return from_candid_variant_n55(_uploadFile, _downloadFile, value);
}
function from_candid_CafResult_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CafResult): CafResult {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_OrderStatus_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_Order_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentMethod_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentMethod): PaymentMethod {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_ProductCategory_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProductCategory): ProductCategory {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_ProductWithQuantity_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProductWithQuantity): ProductWithQuantity {
    return from_candid_record_n45(_uploadFile, _downloadFile, value);
}
function from_candid_Product_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Product): Product {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_ReturnReason_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReturnReason): ReturnReason {
    return from_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function from_candid_ReturnRequest_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReturnRequest): ReturnRequest {
    return from_candid_record_n37(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n48(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    featured: boolean;
    inStock: boolean;
    name: string;
    howToUse: string;
    imageUrl: string;
    shortDescription: string;
    category: _ProductCategory;
    benefits: Array<string>;
    safetyInfo: string;
    fullDescription: string;
    price: bigint;
    ingredients: Array<string>;
}): {
    id: string;
    featured: boolean;
    inStock: boolean;
    name: string;
    howToUse: string;
    imageUrl: string;
    shortDescription: string;
    category: ProductCategory;
    benefits: Array<string>;
    safetyInfo: string;
    fullDescription: string;
    price: bigint;
    ingredients: Array<string>;
} {
    return {
        id: value.id,
        featured: value.featured,
        inStock: value.inStock,
        name: value.name,
        howToUse: value.howToUse,
        imageUrl: value.imageUrl,
        shortDescription: value.shortDescription,
        category: from_candid_ProductCategory_n25(_uploadFile, _downloadFile, value.category),
        benefits: value.benefits,
        safetyInfo: value.safetyInfo,
        fullDescription: value.fullDescription,
        price: value.price,
        ingredients: value.ingredients
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    paymentMethod: _PaymentMethod;
    deliveredAt: [] | [_Time];
    orderStatus: _OrderStatus;
    userId: Principal;
    createdAt: _Time;
    orderId: string;
    updatedAt: _Time;
    totalAmount: bigint;
    customerDetails: _CustomerDetails;
    shippingAddress: _Address;
    returnRequests: Array<_ReturnRequest>;
    cancelReason: [] | [string];
    items: Array<_ProductWithQuantity>;
}): {
    paymentMethod: PaymentMethod;
    deliveredAt?: Time;
    orderStatus: OrderStatus;
    userId: Principal;
    createdAt: Time;
    orderId: string;
    updatedAt: Time;
    totalAmount: bigint;
    customerDetails: CustomerDetails;
    shippingAddress: Address;
    returnRequests: Array<ReturnRequest>;
    cancelReason?: string;
    items: Array<ProductWithQuantity>;
} {
    return {
        paymentMethod: from_candid_PaymentMethod_n30(_uploadFile, _downloadFile, value.paymentMethod),
        deliveredAt: record_opt_to_undefined(from_candid_opt_n32(_uploadFile, _downloadFile, value.deliveredAt)),
        orderStatus: from_candid_OrderStatus_n33(_uploadFile, _downloadFile, value.orderStatus),
        userId: value.userId,
        createdAt: value.createdAt,
        orderId: value.orderId,
        updatedAt: value.updatedAt,
        totalAmount: value.totalAmount,
        customerDetails: value.customerDetails,
        shippingAddress: value.shippingAddress,
        returnRequests: from_candid_vec_n35(_uploadFile, _downloadFile, value.returnRequests),
        cancelReason: record_opt_to_undefined(from_candid_opt_n42(_uploadFile, _downloadFile, value.cancelReason)),
        items: from_candid_vec_n43(_uploadFile, _downloadFile, value.items)
    };
}
function from_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: {
        pending: null;
    } | {
        approved: null;
    } | {
        rejected: null;
    };
    requestId: string;
    requestType: {
        replace: null;
    } | {
        returnItem: null;
    };
    requestedAt: _Time;
    reason: _ReturnReason;
}): {
    status: Variant_pending_approved_rejected;
    requestId: string;
    requestType: Variant_replace_returnItem;
    requestedAt: Time;
    reason: ReturnReason;
} {
    return {
        status: from_candid_variant_n38(_uploadFile, _downloadFile, value.status),
        requestId: value.requestId,
        requestType: from_candid_variant_n39(_uploadFile, _downloadFile, value.requestType),
        requestedAt: value.requestedAt,
        reason: from_candid_ReturnReason_n40(_uploadFile, _downloadFile, value.reason)
    };
}
function from_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    quantity: bigint;
    price: bigint;
    product: _Product;
}): {
    quantity: bigint;
    price: bigint;
    product: Product;
} {
    return {
        quantity: value.quantity,
        price: value.price,
        product: from_candid_Product_n23(_uploadFile, _downloadFile, value.product)
    };
}
function from_candid_record_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    items: Array<_ProductWithQuantity>;
    subtotal: bigint;
}): {
    items: Array<ProductWithQuantity>;
    subtotal: bigint;
} {
    return {
        items: from_candid_vec_n43(_uploadFile, _downloadFile, value.items),
        subtotal: value.subtotal
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Product;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Product;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Product_n23(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ayurvedicCare: null;
} | {
    immunity: null;
} | {
    digestiveHealth: null;
} | {
    fitness: null;
} | {
    multivitamins: null;
} | {
    herbalSupplements: null;
}): ProductCategory {
    return "ayurvedicCare" in value ? ProductCategory.ayurvedicCare : "immunity" in value ? ProductCategory.immunity : "digestiveHealth" in value ? ProductCategory.digestiveHealth : "fitness" in value ? ProductCategory.fitness : "multivitamins" in value ? ProductCategory.multivitamins : "herbalSupplements" in value ? ProductCategory.herbalSupplements : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cod: null;
} | {
    upi: null;
} | {
    netbanking: null;
} | {
    card: null;
}): PaymentMethod {
    return "cod" in value ? PaymentMethod.cod : "upi" in value ? PaymentMethod.upi : "netbanking" in value ? PaymentMethod.netbanking : "card" in value ? PaymentMethod.card : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    shipped: null;
} | {
    cancelled: null;
} | {
    pending: null;
} | {
    delivered: null;
} | {
    confirmed: null;
}): OrderStatus {
    return "shipped" in value ? OrderStatus.shipped : "cancelled" in value ? OrderStatus.cancelled : "pending" in value ? OrderStatus.pending : "delivered" in value ? OrderStatus.delivered : "confirmed" in value ? OrderStatus.confirmed : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): Variant_pending_approved_rejected {
    return "pending" in value ? Variant_pending_approved_rejected.pending : "approved" in value ? Variant_pending_approved_rejected.approved : "rejected" in value ? Variant_pending_approved_rejected.rejected : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    replace: null;
} | {
    returnItem: null;
}): Variant_replace_returnItem {
    return "replace" in value ? Variant_replace_returnItem.replace : "returnItem" in value ? Variant_replace_returnItem.returnItem : value;
}
function from_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    DamagedInShipment: null;
} | {
    WrongProduct: null;
} | {
    Defective: null;
}): ReturnReason {
    return "DamagedInShipment" in value ? ReturnReason.DamagedInShipment : "WrongProduct" in value ? ReturnReason.WrongProduct : "Defective" in value ? ReturnReason.Defective : value;
}
function from_candid_variant_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: string;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Order>): Array<Order> {
    return value.map((x)=>from_candid_Order_n28(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ReturnRequest>): Array<ReturnRequest> {
    return value.map((x)=>from_candid_ReturnRequest_n36(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ProductWithQuantity>): Array<ProductWithQuantity> {
    return value.map((x)=>from_candid_ProductWithQuantity_n44(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Product>): Array<Product> {
    return value.map((x)=>from_candid_Product_n23(_uploadFile, _downloadFile, x));
}
function to_candid_OrderStatus_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): _OrderStatus {
    return to_candid_variant_n57(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentMethod_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): _PaymentMethod {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid_ProductCategory_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductCategory): _ProductCategory {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_ProductInput_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductInput): _ProductInput {
    return to_candid_record_n20(_uploadFile, _downloadFile, value);
}
function to_candid_Product_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Product): _Product {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_ReturnReason_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReturnReason): _ReturnReason {
    return to_candid_variant_n53(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductCategory | null): [] | [_ProductCategory] {
    return value === null ? candid_none() : candid_some(to_candid_ProductCategory_n10(_uploadFile, _downloadFile, value));
}
function to_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    description: string;
    howToUse: string;
    stock: bigint;
    imageUrl: string;
    isFeatured: boolean;
    category: ProductCategory;
    benefits: string;
    safetyInfo: string;
    price: bigint;
    ingredients: string;
}): {
    name: string;
    description: string;
    howToUse: string;
    stock: bigint;
    imageUrl: string;
    isFeatured: boolean;
    category: _ProductCategory;
    benefits: string;
    safetyInfo: string;
    price: bigint;
    ingredients: string;
} {
    return {
        name: value.name,
        description: value.description,
        howToUse: value.howToUse,
        stock: value.stock,
        imageUrl: value.imageUrl,
        isFeatured: value.isFeatured,
        category: to_candid_ProductCategory_n10(_uploadFile, _downloadFile, value.category),
        benefits: value.benefits,
        safetyInfo: value.safetyInfo,
        price: value.price,
        ingredients: value.ingredients
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    featured: boolean;
    inStock: boolean;
    name: string;
    howToUse: string;
    imageUrl: string;
    shortDescription: string;
    category: ProductCategory;
    benefits: Array<string>;
    safetyInfo: string;
    fullDescription: string;
    price: bigint;
    ingredients: Array<string>;
}): {
    id: string;
    featured: boolean;
    inStock: boolean;
    name: string;
    howToUse: string;
    imageUrl: string;
    shortDescription: string;
    category: _ProductCategory;
    benefits: Array<string>;
    safetyInfo: string;
    fullDescription: string;
    price: bigint;
    ingredients: Array<string>;
} {
    return {
        id: value.id,
        featured: value.featured,
        inStock: value.inStock,
        name: value.name,
        howToUse: value.howToUse,
        imageUrl: value.imageUrl,
        shortDescription: value.shortDescription,
        category: to_candid_ProductCategory_n10(_uploadFile, _downloadFile, value.category),
        benefits: value.benefits,
        safetyInfo: value.safetyInfo,
        fullDescription: value.fullDescription,
        price: value.price,
        ingredients: value.ingredients
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductCategory): {
    ayurvedicCare: null;
} | {
    immunity: null;
} | {
    digestiveHealth: null;
} | {
    fitness: null;
} | {
    multivitamins: null;
} | {
    herbalSupplements: null;
} {
    return value == ProductCategory.ayurvedicCare ? {
        ayurvedicCare: null
    } : value == ProductCategory.immunity ? {
        immunity: null
    } : value == ProductCategory.digestiveHealth ? {
        digestiveHealth: null
    } : value == ProductCategory.fitness ? {
        fitness: null
    } : value == ProductCategory.multivitamins ? {
        multivitamins: null
    } : value == ProductCategory.herbalSupplements ? {
        herbalSupplements: null
    } : value;
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): {
    cod: null;
} | {
    upi: null;
} | {
    netbanking: null;
} | {
    card: null;
} {
    return value == PaymentMethod.cod ? {
        cod: null
    } : value == PaymentMethod.upi ? {
        upi: null
    } : value == PaymentMethod.netbanking ? {
        netbanking: null
    } : value == PaymentMethod.card ? {
        card: null
    } : value;
}
function to_candid_variant_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReturnReason): {
    DamagedInShipment: null;
} | {
    WrongProduct: null;
} | {
    Defective: null;
} {
    return value == ReturnReason.DamagedInShipment ? {
        DamagedInShipment: null
    } : value == ReturnReason.WrongProduct ? {
        WrongProduct: null
    } : value == ReturnReason.Defective ? {
        Defective: null
    } : value;
}
function to_candid_variant_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): {
    shipped: null;
} | {
    cancelled: null;
} | {
    pending: null;
} | {
    delivered: null;
} | {
    confirmed: null;
} {
    return value == OrderStatus.shipped ? {
        shipped: null
    } : value == OrderStatus.cancelled ? {
        cancelled: null
    } : value == OrderStatus.pending ? {
        pending: null
    } : value == OrderStatus.delivered ? {
        delivered: null
    } : value == OrderStatus.confirmed ? {
        confirmed: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
